services:
  npl_api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./app/data:/app/app/data
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload